from src.pipeline.functions.quantization.neural_compressor_dynamic_quantization import NeuralCompressorDynamicQuantization
from src.pipeline.functions.quantization.neural_compressor_static_quantization import NeuralCompressorStaticQuantization
from src.pipeline.functions.quantization.pytorch_dynamic_quantization import PytorchDynamicQuantization
from src.pipeline.functions.loader.loader import Loader