from src.pipeline.functions.quantization.neural_compressor_dynamic_quantization import NeuralCompressorDynamicQuantization
from src.pipeline.functions.quantization.pytorch_dynamic_quantization import PytorchDynamicQuantization
